-- Create the Banking Management System Database
CREATE DATABASE BankingSystem;
USE BankingSystem;

-- Create the CUSTOMERS Table
CREATE TABLE CUSTOMERS (
    C_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL
);

-- Create the ACCOUNTS Table
CREATE TABLE ACCOUNTS (
    A_ID INT AUTO_INCREMENT PRIMARY KEY,
    C_ID INT NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID)
);

-- Create the TRANSACTIONS Table
CREATE TABLE TRANSACTIONS (
    T_ID INT AUTO_INCREMENT PRIMARY KEY,
    A_ID INT NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TRANSACTION_TYPE VARCHAR(10) NOT NULL CHECK (TRANSACTION_TYPE IN ('DEPOSIT', 'WITHDRAWAL')),
    FOREIGN KEY (A_ID) REFERENCES ACCOUNTS(A_ID)
);

-- Insert sample data into CUSTOMERS
INSERT INTO CUSTOMERS (NAME, AGE, GENDER, EMAIL)
VALUES
    ("John Doe", 30, "M", "john.doe@example.com"),
    ("Jane Smith", 28, "F", "jane.smith@example.com");

-- Insert sample data into ACCOUNTS
INSERT INTO ACCOUNTS (C_ID, ACCOUNT_TYPE, BALANCE)
VALUES
    (1, "Savings", 5000.00),
    (2, "Checking", 2500.00);

-- Insert sample data into TRANSACTIONS
INSERT INTO TRANSACTIONS (A_ID, TRANSACTION_DATE, AMOUNT, TRANSACTION_TYPE)
VALUES
    (1, '2024-11-01', 1000.00, 'DEPOSIT'),
    (2, '2024-11-02', 500.00, 'WITHDRAWAL');

-- Retrieve data from DOCTORS table
SELECT * FROM CUSTOMERS;

-- Retrieve data from ACCOUNTS table
SELECT * FROM ACCOUNTS;

-- Retrieve data from TRANSACTIONS table
SELECT * FROM TRANSACTIONS;
